### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Nelliza** [OlyaSkoroded/projectSummary2.0#17]
К сожалению, у меня не сходится PerfectPixel
![1](https://user-images.githubusercontent.com/19621113/70394580-7b109900-1a07-11ea-86e9-bce8a28e90db.png)

Выложи плиз скрин макета с PerfectPixel (желательно в инверсии) с открытым окошком его настроек

**Comment by OlyaSkoroded** [comment]
![pxp1](https://user-images.githubusercontent.com/43029118/70846788-9cea9f80-1e8f-11ea-9e10-61e8adfda6d3.png)

**Comment by OlyaSkoroded** [comment]
![pxp2](https://user-images.githubusercontent.com/43029118/70846826-05d21780-1e90-11ea-9481-96076c0afd04.png)

**Comment by OlyaSkoroded** [comment]
![pxp3](https://user-images.githubusercontent.com/43029118/70846832-1bdfd800-1e90-11ea-9ac5-4a0d84ec525a.png)

**Comment by Nelliza** [comment]
Ввиду небольшой "кривости" самого макета Сергей дал добро забить на PerfectPixel в этом конкретном проекте )
