### ISSUE TITLE
Выравнивание title

### ISSUE THREAD

**Issue by Frolikow** [OlyaSkoroded/projectSummary2.0#3]
В блоке title полоску нужно выравнивать каким-нибудь автоматическим способом, и чтоб она точна была по середине
![image](https://user-images.githubusercontent.com/25764783/60946905-9ae94700-a319-11e9-96c0-6d801a04d6fb.png)

**Comment by Frolikow** [comment]
Я видимо не конкретно выразился) тут речь о вертикальном выравнивании, полоска должна быть точно посередине текста

**Comment by OlyaSkoroded** [comment]
![полоска](https://user-images.githubusercontent.com/43029118/61030390-79569100-a3e7-11e9-9fb3-35a10de5a565.png)
Да нет, выразился корректно) Вроде посередине же:D

**Comment by OlyaSkoroded** [comment]
Открыла на телефоне, теперь вижу, что вниз съезжает)

**Comment by OlyaSkoroded** [comment]
Честно говоря, не знаю пока, что с этим сделать. Посмотрела в разных браузерах вроде нигде не съезжает. Съехала, когда на телефоне открыла, но там ее можно в принципе вообще убрать. Когда у тебя такая картина возникает? 

![](https://user-images.githubusercontent.com/25764783/60946905-9ae94700-a319-11e9-96c0-6d801a04d6fb.png)

**Comment by Frolikow** [comment]
К сожалению дело не маленьком экране
![image](https://user-images.githubusercontent.com/25764783/61187281-e1cc9900-a699-11e9-8867-b706d97fabf3.png)
в хроме, без масштабирования, у меня все полоски ниже центра

**Comment by Frolikow** [comment]
Увы, попытка не удачная опять)
Я посмотрел внимательно в чем проблема. У тебя оказалось что текст в блоке title чуть выше середины расположен. Надо его приспустить) как вариант можно ему задать позиционирование
