### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [OlyaSkoroded/projectSummary2.0#4]
На блоках нельзя использовать марджины и паддинги. Если нужен внешний отступ, то лучше создать обертку, которая будет яв-ся элементом родительского блока и ее позиционировать. Внутренние отступы так же лучше задавать элементам а не блоку.

**Comment by OlyaSkoroded** [comment]
Вроде бы исправила, если еще где-то остались, можно плиз конкретный пример)

**Comment by Frolikow** [comment]
По нашим стандартам - нежелательно использовать примеси. 
Здесь у тебя одна сущность и блок и элемент блока `${blockType}`
```pug  
div(class= `title ${blockType}__title`) 
```

**Comment by Frolikow** [comment]
В миксине должен лежать блок с таким же именем как у миксина

**Comment by Frolikow** [comment]
по БЭМу селекторы по тегу не допускаются, только по классам. Если все элементы будут покрыты  классами, такой проблемы никогда не возникнет

**Comment by Frolikow** [comment]
Все ок)
Идем дальше : 
+ очень смущает этот участок кода
![image](https://user-images.githubusercontent.com/25764783/61187322-54d60f80-a69a-11e9-9181-d30e057aae19.png)
элемент внутри самого себя(если смотреть на имя класса), и из-за этого в стилях пришлось писать как попало. Надо подумать как здесь переделать. Можно например сразу в начале цикла проверять условие, и в зависимости от него добавлять модификатор или нет.

+ Здесь у тебя блок внутри блока
![image](https://user-images.githubusercontent.com/25764783/61187399-ecd3f900-a69a-11e9-9de0-4e2a1a08a552.png)

+ 
![image](https://user-images.githubusercontent.com/25764783/61187413-0b39f480-a69b-11e9-8479-9c5dca2b6478.png)
здесь у тебя глядя на элемент, понятно что это элементы блока `software-wrapper`. Но где этот блок?)

**Comment by Frolikow** [comment]
На счет блока` .skill-item`:
1) в стилях не забывай придерживаться общего стиля и расставлять отступы между правилами для классов
2) `ul.skill-item__circles` - а если я захочу чтоб у меня там звездочки были?) вместе со стилями еще и класс придется искать/менять) лучше придумать более общее название, например `point`
3) не понял данный код:
![image](https://user-images.githubusercontent.com/25764783/61314531-030ec000-a827-11e9-861f-c0db27a3b3c9.png)
зачем писать стили через соседний  селектор? можно ведь по дефолту сделать один цвет для `__level`, а `__level_active` закрашивать в нужный цвет? (подсказка: тут явно проблема в логике цикла внутри миксина)
___
по блоку `software` все ок
___
по блоку` software-wrapper`: 
+ опять нарушается БЭМ, т.к. каждый блок это не зависимая сущность. И блок не должен лежать внутри другого блока, как сейчас получилось. Нужно подумать как переименовать, чтобы `software-wrapper` и все что внутри этого блока - было элементами родительского блока `container`. Или мб придумаешь лучше вариант)
